#include <stddef.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

#include <openenclave/seal.h>

#include "sgx_playground/datasealing/common.h"

#include "dispatcher.h"


typedef struct _sealed_data_t
{
  unsigned char optional_message[MAX_OPTIONAL_MESSAGE_SIZE];
  size_t sealed_blob_size;
} sealed_data_t;

int seal_data(
  int seal_policy,
  const unsigned char* opt_mgs,
  size_t opt_msg_len,
  const unsigned char* data,
  size_t data_size,
  data_t* sealed_data
) {
  oe_result_t ret;
  uint8_t* blob = NULL;
  size_t blob_size = 0;
  sealed_data_t* temp = NULL;
  unsigned char* transformed = NULL;
  size_t transformed_size = 0;

  if(opt_msg_len > sizeof(temp->optional_message)) {
    return (int) OE_INVALID_PARAMETER;
  }

  // Transform the plaintext before sealing.
  if(transform_data(data, data_size, &transformed, &transformed_size) != 0) {
    ret = OE_OUT_OF_MEMORY;
    goto exit;
  }

  // Seal the transformed data.
  const oe_seal_setting_t settings[] = { OE_SEAL_SET_POLICY(seal_policy) };
  fprintf(
    stderr,
    "Enclave: Sealing - plaintext: \"%.*s\" => transformed: \"%.*s\"",
    (int)data_size, (const char*)data,
    (int)transformed_size, (const char*)transformed
  );
  if (opt_mgs != NULL) {
    fprintf(stderr, ", optional message: \"%.*s\"", (int)opt_msg_len, (const char*)opt_mgs);
  }
  fprintf(stderr, "\n");
  ret = oe_seal(
    NULL,                                  // `plugin_id`:            NULL = use default sealing plugin
    settings,                              // `settings`:             array of sealing settings (e.g. sealing policy)
    sizeof(settings) / sizeof(*settings),  // `settings_cnt`:         number of elements in settings array
    transformed,                           // `plaintext`:            transformed data to be sealed
    transformed_size,                      // `plaintext_size`:       size of transformed data in bytes
    opt_mgs,                               // `additional_data`:      optional message/additional authenticated data (can be NULL)
    opt_msg_len,                           // `additional_data_size`: size of additional data in bytes (0 if NULL)
    // !!!: `blob` will be allocated by `oe_seal` and we take ownership of it.
    &blob,                                 // `blob`:                 output pointer to receive sealed data blob
    &blob_size                             // `blob_size`:            output pointer to receive size of sealed blob
  );
  if(ret != OE_OK) {
    goto exit;
  }
  fprintf(
    stderr,
    "Enclave: Sealed - sealed blob (%zu bytes): \"",
    blob_size
  );
  for (size_t i = 0; i < blob_size; i++) {
    fprintf(stderr, "%02x", blob[i]);
  }
  if (opt_mgs != NULL) {
    fprintf(stderr, "\", optional message: \"%.*s\"", (int)opt_msg_len, (const char*)opt_mgs);
  }
  fprintf(stderr, "\n");

  // Copy the sealed blob and optional message into the output buffer.
  temp = (sealed_data_t *) malloc(sizeof(*temp) + blob_size);
  if(!temp) {
    ret = OE_OUT_OF_MEMORY;
    goto exit;
  }
  memset(temp, 0, sizeof(*temp));
  if(opt_mgs && opt_msg_len > 0) {
    memcpy(temp->optional_message, opt_mgs, opt_msg_len);
  }
  temp->sealed_blob_size = blob_size;
  memcpy(temp + 1, blob, blob_size);

  // Set output argument; `data_t` is defined in `datasealing_args.h` generated by oeedger8r
  // typedef struct data_t {
  //   uint8_t* data;
  //   size_t size;
  // } data_t;
  sealed_data->data = (uint8_t*) temp;
  sealed_data->size = sizeof(*temp) + blob_size;

exit:
  if(ret != OE_OK && temp) {
    // ELD stub takes ownership of `temp` (it has been assigned to output argument).
    free(temp);
  }
  if(blob) {
    // Clean-up `blob` (it is intermediate ciphertext generated by `oe_seal` that has been memcopied into `temp`).
    free(blob);
  }
  if(transformed) {
    // Clean-up intermediate transformed buffer.
    free(transformed);
  }
  return (int) ret;
}

int unseal_data(
  const data_t* sealed_data,
  const int opt_msg_flag,
  data_t* output_data
) {
  oe_result_t ret;
  const sealed_data_t* unwrapped_sealed_data = (sealed_data_t*) sealed_data->data;
  uint8_t* plaintext = NULL;
  size_t plaintext_size = 0;

  if(sealed_data->size != sizeof(*unwrapped_sealed_data) + unwrapped_sealed_data->sealed_blob_size) {
    ret = OE_INVALID_PARAMETER;
    goto exit;
  }

  // Unseal the data.
  fprintf(
    stderr,
    "Enclave: Unsealing - sealed blob (%zu bytes): \"",
    (size_t)unwrapped_sealed_data->sealed_blob_size
  );
  for (size_t i = 0; i < unwrapped_sealed_data->sealed_blob_size; i++) {
    fprintf(stderr, "%02x", ((const uint8_t*)(unwrapped_sealed_data + 1))[i]);
  }
  size_t opt_msg_actual_len = (opt_msg_flag == 1)
    ? strnlen((const char*)unwrapped_sealed_data->optional_message, sizeof(unwrapped_sealed_data->optional_message))
    : 0
  ;
  if (opt_msg_flag == 1) {
    fprintf(
      stderr,
      "\", optional message: \"%.*s\"",
      (int)opt_msg_actual_len,
      (const char*)unwrapped_sealed_data->optional_message
    );
  }
  fprintf(stderr, "\n");
  ret = oe_unseal(
    (const uint8_t*) (unwrapped_sealed_data + 1),                                            // blob:                 sealed blob starts immediately after the header struct
    unwrapped_sealed_data->sealed_blob_size,                                                 // blob_size:            size of the sealed blob in bytes
    (opt_msg_flag == 1) ? unwrapped_sealed_data->optional_message : NULL,                    // additional_data:      optional authenticated data used during sealing, NULL if not used
    opt_msg_actual_len,                                                                      // additional_data_size: length of additional data, 0 if not used
    // !!!: `plaintext` will be allocated by `oe_unseal` and we take ownership of it.
    &plaintext,                                                                              // plaintext:            output pointer to receive decrypted data
    &plaintext_size                                                                          // plaintext_size:       output pointer to receive size of decrypted data
  );
  if(ret != OE_OK) {
    goto exit;
  }
  fprintf(stderr, "Enclave: Unsealed - transformed plaintext: \"%.*s\"", (int)plaintext_size, (const char*)plaintext);
  if (opt_msg_flag == 1) {
    fprintf(stderr, ", optional message: \"%.*s\"", (int)opt_msg_actual_len, (const char*)unwrapped_sealed_data->optional_message);
  }
  fprintf(stderr, "\n");

  // Set output argument; `data_t` is defined in `datasealing_args.h` generated by oeedger8r
  // typedef struct data_t {
  //   uint8_t* data;
  //   size_t size;
  // } data_t;
  output_data->data = plaintext;
  output_data->size = plaintext_size;

exit:
  // Caller takes ownership of `plaintext` (it has been assigned to output argument).
  return (int) ret;
}


// vim: ts=2 sw=2 et:


