#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "hello_t.h"  // generated by oeedger8r


void enclave_hello(void) {
  // This runs inside the enclave (trusted world).

  {
    // The simplest way to do an ocall.
    oe_result_t result = host_hello();  // ocall back to host
    if(result != OE_OK) {
      fprintf(
        stderr,
        "host_helloworld ocall failed: %s\n",
        oe_result_str(result)
      );
    }
  }
  {
    // The return value of an ocall is returned via an output argument. The return value of the ocall itself is an `oe_result_t`.
    // This is handled automatically by the generated code from oeedger8r: The first argument of the ocall is the output.
    double e_from_host = 0;
    oe_result_t result = host_get_const(&e_from_host, 'e');  // ocall back to host
    if(result != OE_OK) {
      fprintf(
        stderr,
        "host_helloworld ocall failed: %s\n",
        oe_result_str(result)
      );
    }
    fprintf(
      stderr,
      "Hello world from the enclave! The host says e = %f\n",
      e_from_host
    );
  }

  // Allocate some dynamic memory inside the enclave. This is just to demonstrate that the enclave can do dynamic memory allocation.
  {
    char *dynamic_memory = NULL;
    for(size_t i = 256; i > 0 && dynamic_memory == NULL; i--) { // hello.conf: `NumHeapPages=256`
      const size_t page_size = 4096;
      const size_t dynamic_memory_size = i * page_size;
      fprintf(
        stderr,
        "Trying to allocate dynamic memory inside the enclave: %zux%zu=%zu bytes (%.2f MiB)\n",
        i,
        page_size,
        dynamic_memory_size,
        (double) dynamic_memory_size / (1024*1024)
      );
      dynamic_memory = malloc(dynamic_memory_size);
      if(dynamic_memory != NULL) {
        memset(dynamic_memory, 0, dynamic_memory_size);
        fprintf(stderr, "Successfully allocated dynamic memory inside the enclave\n");
      }
      else {
        // If there is no more memory available inside the enclave, malloc will fail and return `NULL`.
        // NOTE: There is no overcommit/OOM killer inside the enclave.
        fprintf(stderr, "Failed to allocate dynamic memory inside the enclave\n");
      }
    }
    if(dynamic_memory != NULL) {
      fprintf(
        stderr,
        "Freeing the allocated dynamic memory inside the enclave\n"
      );
      free(dynamic_memory);
    }
  }
}


// vim: ts=2 sw=2 et:


