#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include <openenclave/host.h>

#include "sgx_playground/datasealing/common.h"

#include "datasealing_u.h"  // generated by oeedger8r


static const char* g_plaintext = "test plaintext";
static const char* g_opt_msg   = "optional sealing message";


static oe_enclave_t* load(
  const char* path,
  uint32_t flags
) {
  oe_enclave_t* enclave = NULL;
  oe_result_t result = oe_create_datasealing_enclave(
    path,
    OE_ENCLAVE_TYPE_SGX,
    flags,
    NULL,
    0,
    &enclave
  );
  if(result != OE_OK) {
    fprintf(
      stderr,
      "oe_create_datasealing_enclave(%s): %s\n",
      path,
      oe_result_str(result)
    );
    goto exit;
  }
exit:
  return enclave;
}

static int try_unseal_and_verify(
  oe_enclave_t* enclave,
  const data_t* sealed,
  const int opt_msg_flag,
  const unsigned char* expected,
  size_t expected_size
) {
  int ret;

  unsigned char* expected_transformed = NULL;
  size_t expected_transformed_size = 0;
  if(transform_data(expected, expected_size, &expected_transformed, &expected_transformed_size) != 0) {
    ret = ERROR_OUT_OF_MEMORY;
    goto exit;
  }

  int retval;
  data_t unsealed = {
    // uint8_t* data;
    NULL,
    // size_t size;
    0
  };
  oe_result_t result = enclave_unseal_data(
    enclave,
    &retval,
    sealed,
    opt_msg_flag,
    // !!!: `unsealed.data` will be allocated by `enclave_unseal_data` and we take ownership of it.
    &unsealed
  );
  if(result != OE_OK || retval != 0) {
    ret = ERROR_UNSEAL_FAIL;
    goto exit;
  }

  if(unsealed.data == NULL) {
    fprintf(stderr, "Host: Unsealed data is NULL\n");
    ret = ERROR_UNSEALED_DATA_FAIL;
    goto exit;
  }
  if(expected_transformed_size != unsealed.size) {
    fprintf(stderr, "Host: Unsealed data size mismatch: expected=%zu, actual=%zu\n", expected_transformed_size, unsealed.size);
    ret = ERROR_UNSEALED_DATA_FAIL;
    goto exit;
  }

  int cmp = strncmp(
      (const char*) unsealed.data,
      (const char*) expected_transformed,
      expected_transformed_size
  );
  if(cmp != 0) {
    fprintf(stderr, "Host: Unsealed data content mismatch\n");
    ret = ERROR_UNSEALED_DATA_FAIL;
    goto exit;
  }

  ret = 0;

exit:
  if(unsealed.data != NULL) {
    free(unsealed.data);
  }
  if(expected_transformed != NULL) {
    free(expected_transformed);
  }
  return ret;
}

static int run(
  oe_enclave_t* enclave_seal,
  oe_enclave_t* enclave_unseal,
  int seal_policy,
  const unsigned char* opt_mgs,
  size_t opt_msg_len,
  const unsigned char* data,
  size_t data_size
) {
  int ret;

  fprintf(stderr, "Host: Seal data with policy: %s\n", GET_POLICY_NAME(seal_policy));

  int retval;
  data_t sealed = {
    // uint8_t* data;
    NULL,
    // size_t size;
    0
  };
  oe_result_t oe_result = enclave_seal_data(
    enclave_seal,
    &retval,
    seal_policy,
    opt_mgs,
    opt_msg_len,
    data,
    data_size,
    // !!!: `sealed.data` will be allocated by `enclave_seal_data` and we take ownership of it.
    &sealed
  );
  if((oe_result != OE_OK) || (retval != 0)) {
    fprintf(stderr, "Host: seal_data failed: %s, retval=%d\n", oe_result_str(oe_result), retval);
    ret = ERROR_SEAL_FAIL;
    goto exit;
  }
  fprintf(stderr, "Host: data successfully sealed\n");

  fprintf(stderr, "Host: Unseal data\n");
  int result = try_unseal_and_verify(
    enclave_unseal,
    &sealed,
    opt_mgs != NULL && opt_msg_len > 0,
    data,
    data_size
  );
  if(result != 0) {
    fprintf(stderr, "Host: Validation of unsealed data failed: result=%d\n", result);
    ret = result;
    goto exit;
  }
  fprintf(stderr, "Host: Validation of unsealed data succeeded\n");
  ret = 0;

exit:
  if(sealed.data != NULL) {
    // Clean-up `sealed.data` (it was allocated by `enclave_seal_data` and we took ownership of it).
    free(sealed.data);
  }
  return ret;
}

int main(int argc, const char* argv[]) {
  const char* const oe_simulate = getenv("OE_SIMULATE");
  const uint32_t enclave_flags = (
    OE_ENCLAVE_FLAG_DEBUG
    |
    ((oe_simulate != NULL && oe_simulate[0] == '1' && oe_simulate[0] != '\0')
      ? (uint32_t)OE_ENCLAVE_FLAG_SIMULATE
      : 0u
    )
  );

  int ret;
  oe_enclave_t* enclave_a_v1 = NULL;
  oe_enclave_t* enclave_a_v2 = NULL;
  oe_enclave_t* enclave_b = NULL;

  if(argc != 4) {
    fprintf(stderr, "Usage: %s <a_v1.signed> <a_v2.signed> <b.signed>\n", argv[0]);
    ret = EXIT_FAILURE;
    goto exit;
  }

  fprintf(
    stderr,
    "Host: Loading enclaves: enclave_flags=0x%08x (debug mode: %s, simulation mode: %s)\n",
    enclave_flags,
    (enclave_flags & OE_ENCLAVE_FLAG_DEBUG) ? "ON" : "OFF",
    (enclave_flags & OE_ENCLAVE_FLAG_SIMULATE) ? "ON" : "OFF"
  );
  enclave_a_v1 = load(argv[1], enclave_flags);
  if(enclave_a_v1 == NULL) {
    ret = EXIT_FAILURE;
    goto exit;
  }
  enclave_a_v2 = load(argv[2], enclave_flags);
  if(enclave_a_v2 == NULL) {
    ret = EXIT_FAILURE;
    goto exit;
  }
  enclave_b = load(argv[3], enclave_flags);
  if(enclave_b == NULL) {
    ret = EXIT_FAILURE;
    goto exit;
  }

  // POLICY          | Sealer      | Unsealer    | Expected
  // ----------------|-------------|-------------|----------
  // POLICY_UNIQUE   | A v1        | A v1        | SUCCESS
  // POLICY_UNIQUE   | A v1        | A v2        | FAIL      (OE_CRYPTO_ERROR)
  // POLICY_UNIQUE   | A v2        | A v1        | FAIL      (OE_CRYPTO_ERROR)
  // POLICY_UNIQUE   | A v1        | B           | FAIL      (OE_CRYPTO_ERROR)
  // POLICY_PRODUCT  | A v1        | A v1        | SUCCESS
  // POLICY_PRODUCT  | A v1        | A v2        | SUCCESS
  // POLICY_PRODUCT  | A v2        | A v1        | FAIL      (OE_INVALID_ISVSVN)
  // POLICY_PRODUCT  | A v1        | B           | FAIL      (OE_CRYPTO_ERROR)
  size_t success_cnt = 0;
  size_t failure_cnt = 0;

  fprintf(stdout, "\n");
  fprintf(stdout, "========================================\n");
  fprintf(stdout, " SEAL/UNSEAL TESTS  [POLICY_UNIQUE]\n");
  fprintf(stdout, "========================================\n");

  fprintf(stdout, "\n[1/4] Seal: A-v1  Unseal: A-v1  => expect SUCCESS\n");
  ret = run(
    enclave_a_v1,
    enclave_a_v1,
    POLICY_UNIQUE,
    (const unsigned char*) g_opt_msg,
    strlen(g_opt_msg),
    (const unsigned char*) g_plaintext,
    strlen(g_plaintext)
  );
  if(ret != 0) {
    ++failure_cnt;
    fprintf(stdout, "    FAIL  (ret=%s)\n", GET_ERROR_NAME(ret));
  }
  else {
    ++success_cnt;
    fprintf(stdout, "    PASS\n");
  }

  fprintf(stdout, "\n[2/4] Seal: A-v1  Unseal: A-v2  => expect FAIL\n");
  ret = run(
    enclave_a_v1,
    enclave_a_v2,
    POLICY_UNIQUE,
    (const unsigned char*) g_opt_msg,
    strlen(g_opt_msg),
    (const unsigned char*) g_plaintext,
    strlen(g_plaintext)
  );
  if(ret != ERROR_UNSEAL_FAIL) {
    ++failure_cnt;
    fprintf(stdout, "    FAIL  (ret=%s, expected ERROR_UNSEAL_FAIL)\n", GET_ERROR_NAME(ret));
  }
  else {
    ++success_cnt;
    fprintf(stdout, "    PASS\n");
  }

  fprintf(stdout, "\n[3/4] Seal: A-v2  Unseal: A-v1  => expect FAIL\n");
  ret = run(
    enclave_a_v2,
    enclave_a_v1,
    POLICY_UNIQUE,
    (const unsigned char*) g_opt_msg,
    strlen(g_opt_msg),
    (const unsigned char*) g_plaintext,
    strlen(g_plaintext)
  );
  if(ret != ERROR_UNSEAL_FAIL) {
    ++failure_cnt;
    fprintf(stdout, "    FAIL  (ret=%s, expected ERROR_UNSEAL_FAIL)\n", GET_ERROR_NAME(ret));
  }
  else {
    ++success_cnt;
    fprintf(stdout, "    PASS\n");
  }

  fprintf(stdout, "\n[4/4] Seal: A-v1  Unseal: B     => expect FAIL\n");
  ret = run(
    enclave_a_v1,
    enclave_b,
    POLICY_UNIQUE,
    (const unsigned char*) g_opt_msg,
    strlen(g_opt_msg),
    (const unsigned char*) g_plaintext,
    strlen(g_plaintext)
  );
  if(ret != ERROR_UNSEAL_FAIL) {
    ++failure_cnt;
    fprintf(stdout, "    FAIL  (ret=%s, expected ERROR_UNSEAL_FAIL)\n", GET_ERROR_NAME(ret));
  }
  else {
    ++success_cnt;
    fprintf(stdout, "    PASS\n");
  }

  fprintf(stdout, "\n");
  fprintf(stdout, "========================================\n");
  fprintf(stdout, " SEAL/UNSEAL TESTS  [POLICY_PRODUCT]\n");
  fprintf(stdout, "========================================\n");

  fprintf(stdout, "\n[1/4] Seal: A-v1  Unseal: A-v1  => expect SUCCESS\n");
  ret = run(
    enclave_a_v1,
    enclave_a_v1,
    POLICY_PRODUCT,
    (const unsigned char*) g_opt_msg,
    strlen(g_opt_msg),
    (const unsigned char*) g_plaintext,
    strlen(g_plaintext)
  );
  if(ret != 0) {
    ++failure_cnt;
    fprintf(stdout, "    FAIL  (ret=%s)\n", GET_ERROR_NAME(ret));
  }
  else {
    ++success_cnt;
    fprintf(stdout, "    PASS\n");
  }

  fprintf(stdout, "\n[2/4] Seal: A-v1  Unseal: A-v2  => expect SUCCESS\n");
  ret = run(
    enclave_a_v1,
    enclave_a_v2,
    POLICY_PRODUCT,
    (const unsigned char*) g_opt_msg,
    strlen(g_opt_msg),
    (const unsigned char*) g_plaintext,
    strlen(g_plaintext)
  );
  if(ret != 0) {
    ++failure_cnt;
    fprintf(stdout, "    FAIL  (ret=%s)\n", GET_ERROR_NAME(ret));
  }
  else {
    ++success_cnt;
    fprintf(stdout, "    PASS\n");
  }

  fprintf(stdout, "\n[3/4] Seal: A-v2  Unseal: A-v1  => expect FAIL\n");
  ret = run(
    enclave_a_v2,
    enclave_a_v1,
    POLICY_PRODUCT,
    (const unsigned char*) g_opt_msg,
    strlen(g_opt_msg),
    (const unsigned char*) g_plaintext,
    strlen(g_plaintext)
  );
  if(ret != ERROR_UNSEAL_FAIL) {
    ++failure_cnt;
    fprintf(stdout, "    FAIL  (ret=%s, expected ERROR_UNSEAL_FAIL)\n", GET_ERROR_NAME(ret));
  }
  else {
    ++success_cnt;
    fprintf(stdout, "    PASS\n");
  }

  fprintf(stdout, "\n[4/4] Seal: A-v1  Unseal: B     => expect FAIL\n");
  ret = run(
    enclave_a_v1,
    enclave_b,
    POLICY_PRODUCT,
    (const unsigned char*) g_opt_msg,
    strlen(g_opt_msg),
    (const unsigned char*) g_plaintext,
    strlen(g_plaintext)
  );
  if(ret != ERROR_UNSEAL_FAIL) {
    ++failure_cnt;
    fprintf(stdout, "    FAIL  (ret=%s, expected ERROR_UNSEAL_FAIL)\n", GET_ERROR_NAME(ret));
  }
  else {
    ++success_cnt;
    fprintf(stdout, "    PASS\n");
  }

  fprintf(stdout, "\n----------------------------------------\n");
  fprintf(stdout, " Results: %zu passed, %zu failed\n", success_cnt, failure_cnt);
  fprintf(stdout, "========================================\n\n");

exit:
  if(enclave_a_v1 != NULL) {
    oe_terminate_enclave(enclave_a_v1);
    enclave_a_v1 = NULL;
  }
  if(enclave_a_v2 != NULL) {
    oe_terminate_enclave(enclave_a_v2);
    enclave_a_v2 = NULL;
  }
  if(enclave_b != NULL) {
    oe_terminate_enclave(enclave_b);
    enclave_b = NULL;
  }
  return ret;
}


// vim: ts=2 sw=2 et:


