#include <stdio.h>
#include <stdlib.h>

#include <openenclave/host.h>

#include "hello_u.h"  // generated by oeedger8r


// ocall implementation: enclave calls this
void host_hello(void) {
  printf("Hello world from the host\n");
}

// ocall implementation: enclave calls this
double host_get_const(char constant) {
  switch(constant) {
    case 'p':
      return 3.14159265358979323846;  // pi
    case 'e':
      return 2.71828182845904523536;  // e
    default:
      return 0.0;
  }
}


int main(int argc, const char* argv[]) {
  const char* const oe_simulate = getenv("OE_SIMULATE");
  const uint32_t enclave_flags = (
    OE_ENCLAVE_FLAG_DEBUG
    |
    ((oe_simulate != NULL && oe_simulate[0] == '1' && oe_simulate[0] != '\0')
      ? (uint32_t)OE_ENCLAVE_FLAG_SIMULATE
      : 0u
    )
  );

  oe_enclave_t* enclave = NULL;
  oe_result_t result;

  if(argc != 2) {
    fprintf(stderr, "Usage: %s <enclave.signed>\n", argv[0]);
    return EXIT_FAILURE;
  }

  // Load and initialize the signed enclave.
  fprintf(
    stderr,
    "Host: Loading enclave: enclave_flags=0x%08x (debug mode: %s, simulation mode: %s)\n",
    enclave_flags,
    (enclave_flags & OE_ENCLAVE_FLAG_DEBUG) ? "ON" : "OFF",
    (enclave_flags & OE_ENCLAVE_FLAG_SIMULATE) ? "ON" : "OFF"
  );
  result = oe_create_hello_enclave(
    argv[1],  // enclave path
    OE_ENCLAVE_TYPE_SGX,  // enclave type
    enclave_flags,  // enclave flags
    NULL,  // settings
    0,  // settings count
    &enclave  // output argument for the enclave pointer
  );
  if(result != OE_OK) {
    fprintf(
      stderr,
      "oe_create_hello_enclave(): %s\n",
      oe_result_str(result)
    );
    return EXIT_FAILURE;
  }

  // ecall into the enclave
  result = enclave_hello(enclave);
  if(result != OE_OK) {
    fprintf(
      stderr,
      "enclave_helloworld ecall failed: %s\n",
      oe_result_str(result)
    );
  }

  oe_terminate_enclave(enclave);

  return (result == OE_OK) ? EXIT_SUCCESS : EXIT_FAILURE;
}


// vim: ts=2 sw=2 et:


